# Generated by Django 4.0.5 on 2022-07-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='empresa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
    ]
